### ISSUE TITLE
Template name with dash create invalid classnames

### ISSUE THREAD

**Issue by phlppschrr** [Toutouwai/AutoTemplateStubs#2]
Thanks for this module. I just installed it and noticed, that stubs of template names like `basic-page` have invalid code like this `class Page_legal-page extends Page {}`. 

mindplay.dk TemplateStubs replaced dashes with underscores. I think this is a good workaround.

Something like this (line 241):
```
$class_name = $this->class_prefix . str_replace('-',  '_', $template->name);
```

**Comment by Toutouwai** [comment]
Thanks, fixed in v0.1.4.
